export const BLOG_POST_LIST = "BLOG_POST_LIST";
export const BLOG_POST_LIST_SET_PAGE = "BLOG_POST_LIST_SET_PAGE";
export const BLOG_POST_ADD = "BLOG_POST_ADD";

export const BLOG_POST = "BLOG_POST";
export const BLOG_POST_UNLOADED = "BLOG_POST_UNLOADED";

export const LOADING = "LOADING";
export const API_ERROR = "API_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_LOOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_SET = "USER_SET";

export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const IMAGE_UPLOAD_OK = "IMAGE_UPLOAD_OK";
export const IMAGE_UPLOAD_KO = "IMAGE_UPLOAD_KO";
export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";

export const IMAGE_DELETE = "IMAGE_DELETE";
